services:
  database:
    image: postgres:17-alpine
    container_name: dev-postgres-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=local_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_storage: